-- v0.12.0 source-aware expansion schema.
alter table if exists artists
  add column if not exists crawl_depth integer,
  add column if not exists discovered_from_artist_id bigint references artists(id),
  add column if not exists discovery_source text,
  add column if not exists review_status text default 'accepted';

create table if not exists relationship_evidence (
  id bigint generated by default as identity primary key,
  relationship_id bigint not null references relationships(id) on delete cascade,
  source text not null,
  source_url text,
  evidence_text text,
  confidence numeric,
  review_status text not null default 'accepted',
  created_at timestamptz not null default now(),
  unique (relationship_id, source, source_url)
);

create index if not exists relationship_evidence_relationship_idx
  on relationship_evidence(relationship_id);

create index if not exists relationship_evidence_source_idx
  on relationship_evidence(source);

-- Backfill existing relationships as ULAN evidence where no evidence exists.
insert into relationship_evidence
  (relationship_id, source, source_url, evidence_text, confidence, review_status)
select
  r.id,
  'ULAN',
  null,
  'Existing relationship imported from ULAN-backed Trecento dataset.',
  1.0,
  'accepted'
from relationships r
where not exists (
  select 1 from relationship_evidence e where e.relationship_id=r.id
);
