-- v0.12.0 / v0.12.1 source-aware expansion schema — UUID-corrected

alter table public.artists
  add column if not exists crawl_depth integer,
  add column if not exists discovered_from_artist_id uuid
    references public.artists(id),
  add column if not exists discovery_source text;

create table if not exists public.relationship_evidence (
  id bigint generated by default as identity primary key,
  relationship_id uuid not null
    references public.relationships(id) on delete cascade,
  source text not null,
  source_url text,
  evidence_text text,
  confidence numeric,
  review_status text not null default 'accepted',
  created_at timestamptz not null default now()
);

create index if not exists relationship_evidence_relationship_idx
  on public.relationship_evidence(relationship_id);

create index if not exists relationship_evidence_source_idx
  on public.relationship_evidence(source);

alter table public.relationship_evidence enable row level security;

insert into public.relationship_evidence
  (relationship_id, source, source_url, evidence_text, confidence, review_status)
select
  r.id,
  'ULAN',
  null,
  'Existing relationship imported from ULAN-backed Trecento dataset.',
  1.0,
  'accepted'
from public.relationships r
where not exists (
  select 1
  from public.relationship_evidence e
  where e.relationship_id=r.id
    and e.source='ULAN'
);
