
create table if not exists public.low_countries_candidates (
  ulan_id text primary key,
  preferred_name text,
  discovered_label text,
  record_type text,
  birth_year integer,
  death_year integer,
  floruit_start integer,
  floruit_end integer,
  geography_bucket text,
  nationality_text text,
  role_text text,
  seed_connection_count integer not null default 0,
  relationship_score integer not null default 0,
  strongest_relationship text,
  crawl_depth integer not null default 1,
  review_status text not null default 'candidate'
    check (review_status in ('candidate','core_ready','expanded_ready','held','rejected')),
  first_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.low_countries_candidate_edges (
  id bigint generated by default as identity primary key,
  seed_ulan_id text not null,
  candidate_ulan_id text not null,
  candidate_label text,
  relationship_type text not null,
  visual_class text not null,
  directed boolean not null,
  source_url text not null,
  created_at timestamptz not null default now(),
  unique(seed_ulan_id,candidate_ulan_id,relationship_type)
);

create index if not exists low_countries_candidate_edges_candidate_idx
  on public.low_countries_candidate_edges(candidate_ulan_id);

create index if not exists low_countries_candidates_score_idx
  on public.low_countries_candidates(relationship_score desc, seed_connection_count desc);

-- Safety: staging candidates are intentionally NOT foreign-keyed into public.artists.
-- They remain invisible to the production Trecento graph until explicit later admission.
