
create table if not exists public.low_countries_network_edges (
  id bigint generated by default as identity primary key,
  from_ulan_id text not null,
  to_ulan_id text not null,
  relationship_type text not null,
  visual_class text not null,
  directed boolean not null,
  source_url text not null,
  source_depth integer not null check (source_depth in (0,1)),
  created_at timestamptz not null default now(),
  unique(from_ulan_id,to_ulan_id,relationship_type)
);

create index if not exists low_countries_network_edges_from_idx
  on public.low_countries_network_edges(from_ulan_id);

create index if not exists low_countries_network_edges_to_idx
  on public.low_countries_network_edges(to_ulan_id);

-- Copy already-staged seed -> first-degree edges into the generic table.
insert into public.low_countries_network_edges(
  from_ulan_id,to_ulan_id,relationship_type,visual_class,directed,source_url,source_depth
)
select
  seed_ulan_id,candidate_ulan_id,relationship_type,visual_class,directed,source_url,0
from public.low_countries_candidate_edges
on conflict (from_ulan_id,to_ulan_id,relationship_type) do nothing;

-- Existing first-degree candidates remain depth 1.
update public.low_countries_candidates
set crawl_depth = 1
where crawl_depth is null or crawl_depth < 1;
