
create table if not exists public.zeri_associations (
  id bigint generated by default as identity primary key,
  artist_id uuid not null references public.artists(id) on delete cascade,
  related_artist_id uuid not null references public.artists(id) on delete cascade,
  attribution_count integer not null check (attribution_count > 0),
  threshold_used integer not null,
  identity_basis text not null check (identity_basis in ('ULAN','VIAF')),
  source_url text not null,
  updated_at timestamptz not null default now(),
  unique (artist_id, related_artist_id)
);
create index if not exists zeri_associations_artist_idx on public.zeri_associations(artist_id);

create table if not exists public.admin_change_log (
  id bigint generated by default as identity primary key,
  artist_id uuid references public.artists(id) on delete set null,
  action text not null,
  previous_value jsonb,
  new_value jsonb,
  note text,
  created_at timestamptz not null default now()
);
create index if not exists admin_change_log_artist_idx on public.admin_change_log(artist_id);
