-- Art Network Engine 1.0 alpha 1
-- Parallel schema: does not modify or replace the existing 0.20.x network tables.
-- Designed for one generic pipeline shared by every network.

create extension if not exists pgcrypto;

create table if not exists public.v1_artists (
  id uuid primary key default gen_random_uuid(),
  canonical_name text not null,
  entity_type text not null default 'person',
  ulan_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists v1_artists_name_idx on public.v1_artists(lower(canonical_name));

create table if not exists public.v1_networks (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  public_label text,
  description text,
  start_year integer,
  end_year integer,
  geography_notes text,
  methodology_text text,
  role_filter jsonb not null default '[]'::jsonb,
  relationship_families jsonb not null default '["training","influence","collaboration","association","family"]'::jsonb,
  wikipedia_relationships_enabled boolean not null default false,
  max_depth integer not null default 2 check (max_depth between 1 and 2),
  status text not null default 'draft' check (status in ('draft','published','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.v1_network_memberships (
  network_id uuid not null references public.v1_networks(id) on delete cascade,
  artist_id uuid not null references public.v1_artists(id) on delete cascade,
  origin text not null check (origin in ('seed','ulan','curatorial')),
  graph_depth integer not null check (graph_depth between 0 and 2),
  automatic_tier text not null check (automatic_tier in ('core','expanded','comprehensive')),
  manual_tier text check (manual_tier in ('core','expanded','comprehensive')),
  included boolean not null default true,
  curatorial_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (network_id,artist_id)
);
create index if not exists v1_memberships_network_depth_idx on public.v1_network_memberships(network_id,graph_depth,included);

create table if not exists public.v1_ulan_profiles (
  artist_id uuid primary key references public.v1_artists(id) on delete cascade,
  ulan_id text not null unique,
  preferred_name text,
  record_type text,
  aliases jsonb not null default '[]'::jsonb,
  roles jsonb not null default '[]'::jsonb,
  roles_raw text,
  nationalities text,
  period_start integer,
  period_end integer,
  birth_place text,
  death_place text,
  active_places jsonb not null default '[]'::jsonb,
  parsed_snapshot jsonb not null default '{}'::jsonb,
  source_url text,
  source_hash text,
  fetched_at timestamptz not null default now(),
  last_changed_at timestamptz not null default now()
);
create index if not exists v1_ulan_profiles_ulan_idx on public.v1_ulan_profiles(ulan_id);

create table if not exists public.v1_relationship_rules (
  raw_qualifier text primary key,
  reciprocal_qualifier text,
  normalized_family text not null,
  direction_mode text not null check (direction_mode in ('focus_to','counterpart_to','symmetric')),
  directed boolean not null default true,
  visual_class text not null default 'dotted' check (visual_class in ('solid','dashed','dotted')),
  expansion_eligible boolean not null default true,
  render_eligible boolean not null default true,
  getty_code text,
  notes text,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.v1_ulan_relationship_assertions (
  id bigint generated by default as identity primary key,
  focus_artist_id uuid not null references public.v1_artists(id) on delete cascade,
  focus_ulan_id text not null,
  counterpart_ulan_id text not null,
  counterpart_label text,
  raw_qualifier text not null,
  normalized_family text,
  canonical_from_ulan text,
  canonical_to_ulan text,
  directed boolean,
  visual_class text,
  expansion_eligible boolean not null default false,
  render_eligible boolean not null default false,
  mapping_status text not null check (mapping_status in ('mapped','quarantined')),
  raw_context text,
  source_url text,
  source_hash text,
  fetched_at timestamptz not null default now(),
  unique (focus_ulan_id,counterpart_ulan_id,raw_qualifier)
);
create index if not exists v1_ulan_assertions_focus_idx on public.v1_ulan_relationship_assertions(focus_ulan_id);
create index if not exists v1_ulan_assertions_counterpart_idx on public.v1_ulan_relationship_assertions(counterpart_ulan_id);
create index if not exists v1_ulan_assertions_mapping_idx on public.v1_ulan_relationship_assertions(mapping_status,raw_qualifier);

create table if not exists public.v1_unknown_qualifiers (
  raw_qualifier text primary key,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  seen_count integer not null default 1,
  sample_focus_ulan text,
  sample_counterpart_ulan text,
  sample_source_url text,
  review_note text
);

create table if not exists public.v1_network_candidates (
  network_id uuid not null references public.v1_networks(id) on delete cascade,
  ulan_id text not null,
  preferred_name text,
  discovered_depth integer not null check (discovered_depth between 1 and 2),
  source_ulan_ids jsonb not null default '[]'::jsonb,
  source_qualifiers jsonb not null default '[]'::jsonb,
  profile_snapshot jsonb,
  scope_status text not null default 'unresolved' check (scope_status in ('unresolved','eligible','chronology_out','role_out','rejected','admitted')),
  decision_note text,
  updated_at timestamptz not null default now(),
  primary key (network_id,ulan_id)
);
create index if not exists v1_candidates_network_depth_idx on public.v1_network_candidates(network_id,discovered_depth,scope_status);

create table if not exists public.v1_curatorial_overrides (
  network_id uuid not null references public.v1_networks(id) on delete cascade,
  artist_id uuid not null references public.v1_artists(id) on delete cascade,
  display_name text,
  layout_year integer,
  region text,
  tier text check (tier in ('core','expanded','comprehensive')),
  note text,
  updated_at timestamptz not null default now(),
  primary key (network_id,artist_id)
);

create table if not exists public.v1_curatorial_relationships (
  id uuid primary key default gen_random_uuid(),
  network_id uuid not null references public.v1_networks(id) on delete cascade,
  from_artist_id uuid not null references public.v1_artists(id) on delete cascade,
  to_artist_id uuid not null references public.v1_artists(id) on delete cascade,
  normalized_family text not null,
  directed boolean not null default true,
  visual_class text not null default 'dotted' check (visual_class in ('solid','dashed','dotted')),
  note text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists v1_manual_rel_network_idx on public.v1_curatorial_relationships(network_id,active);

create table if not exists public.v1_media_cache (
  artist_id uuid primary key references public.v1_artists(id) on delete cascade,
  wikipedia_url text,
  wikipedia_language text,
  wikidata_id text,
  thumbnail_source_url text,
  storage_path text,
  source_page_url text,
  status text not null default 'unresolved' check (status in ('unresolved','valid','stale','invalid','no_image')),
  resolved_at timestamptz,
  verified_at timestamptz,
  next_check_at timestamptz,
  source_hash text,
  updated_at timestamptz not null default now()
);


create table if not exists public.v1_published_networks (
  network_id uuid primary key references public.v1_networks(id) on delete cascade,
  payload jsonb not null,
  artist_count integer not null default 0,
  relationship_count integer not null default 0,
  content_hash text,
  build_version text not null default '1.0.4',
  published_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists v1_published_networks_published_idx
  on public.v1_published_networks(published_at desc);

create table if not exists public.v1_sync_runs (
  id uuid primary key default gen_random_uuid(),
  network_id uuid references public.v1_networks(id) on delete cascade,
  run_type text not null,
  status text not null default 'running' check (status in ('running','preview','applied','failed')),
  stats jsonb not null default '{}'::jsonb,
  changes jsonb not null default '[]'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  applied_at timestamptz,
  error_text text
);

-- Getty ULAN relationship vocabulary seed. Raw Getty qualifiers remain stored on
-- every assertion. These rules only define deterministic graph semantics.
-- Unknown qualifiers are quarantined instead of guessed.
insert into public.v1_relationship_rules
(raw_qualifier,reciprocal_qualifier,normalized_family,direction_mode,directed,visual_class,expansion_eligible,render_eligible,getty_code,notes)
values
('related to','related to','association','symmetric',false,'dotted',true,true,'1000','Getty general relation'),
('miscellaneous','miscellaneous','other','symmetric',false,'dotted',false,false,'1001','Getty reserves this for problematic data loads'),
('associated with','associated with','association','symmetric',false,'dashed',true,true,'1003','Generic professional association'),
('possibly identified with','possibly identified with','identity','symmetric',false,'dotted',false,false,'1005','Identity uncertainty; never expands network'),
('formerly identified with','formerly identified with','identity','symmetric',false,'dotted',false,false,'1006','Identity history; never expands network'),
('distinguished from','distinguished from','identity','symmetric',false,'dotted',false,false,'1007','Identity distinction; never expands network'),
('meaning / usage overlaps with','meaning / usage overlaps with','identity','symmetric',false,'dotted',false,false,'1008','Not an artistic network edge'),
('teacher of','student of','training','focus_to',true,'solid',true,true,'1101',null),
('student of','teacher of','training','counterpart_to',true,'solid',true,true,'1102',null),
('apprentice of','apprentice was','training','counterpart_to',true,'solid',true,true,'1105',null),
('apprentice was','apprentice of','training','focus_to',true,'solid',true,true,'1106',null),
('influenced','influenced by','influence','focus_to',true,'dashed',true,true,'1107',null),
('influenced by','influenced','influence','counterpart_to',true,'dashed',true,true,'1108',null),
('master of','master was','training','focus_to',true,'solid',true,true,'1111',null),
('master was','master of','training','counterpart_to',true,'solid',true,true,'1112',null),
('fellow student of','fellow student of','training','symmetric',false,'dashed',true,true,'1113',null),
('patron of','patron was','patronage','focus_to',false,'dotted',false,false,'1201',null),
('patron was','patron of','patronage','counterpart_to',false,'dotted',false,false,'1202',null),
('donor of','donor was','patronage','focus_to',false,'dotted',false,false,'1203',null),
('donor was','donor of','patronage','counterpart_to',false,'dotted',false,false,'1204',null),
('client of','client was','patronage','focus_to',false,'dotted',false,false,'1205',null),
('client was','client of','patronage','counterpart_to',false,'dotted',false,false,'1206',null),
('artist to','artist was','patronage','focus_to',false,'dotted',false,false,'1211',null),
('artist was','artist to','patronage','counterpart_to',false,'dotted',false,false,'1212',null),
('court artist to','court artist was','patronage','focus_to',false,'dotted',false,false,'1213',null),
('court artist was','court artist to','patronage','counterpart_to',false,'dotted',false,false,'1214',null),
('employee of','employee was','collaboration','counterpart_to',true,'solid',true,true,'1217',null),
('employee was','employee of','collaboration','focus_to',true,'solid',true,true,'1218',null),
('appointed by','appointed','patronage','counterpart_to',false,'dotted',false,false,'1221',null),
('crowned by','crowned','patronage','counterpart_to',false,'dotted',false,false,'1223',null),
('crowned','crowned by','patronage','focus_to',false,'dotted',false,false,'1224',null),
('colleague of','colleague of','collaboration','symmetric',false,'dashed',true,true,'1300',null),
('associate of','associate of','association','symmetric',false,'dashed',true,true,'1302',null),
('collaborated with','collaborated with','collaboration','symmetric',false,'dashed',true,true,'1303',null),
('worked with','worked with','collaboration','symmetric',false,'dashed',true,true,'1305',null),
('performed with','performed with','collaboration','symmetric',false,'dashed',true,true,'1306',null),
('assistant of','assisted by','collaboration','counterpart_to',true,'solid',true,true,'1307',null),
('assisted by','assistant of','collaboration','focus_to',true,'solid',true,true,'1308',null),
('advisor of','advised by','collaboration','focus_to',true,'dashed',true,true,'1309',null),
('advised by','advisor of','collaboration','counterpart_to',true,'dashed',true,true,'1310',null),
('partner of','partner of','collaboration','symmetric',false,'dashed',true,true,'1311',null),
('partner in','partner was (firm to person)','group','focus_to',false,'dotted',false,false,'1313',null),
('partner was (firm to person)','partner in','group','counterpart_to',false,'dotted',false,false,'1314',null),
('principal in (person to firm)','principal was (firm to person)','group','focus_to',false,'dotted',false,false,'1315',null),
('principal was (firm to person)','principal in (person to firm)','group','counterpart_to',false,'dotted',false,false,'1316',null),
('member of','member was','group','focus_to',false,'dotted',false,false,'1317',null),
('member was','member of','group','counterpart_to',false,'dotted',false,false,'1318',null),
('school of','school was','group','focus_to',false,'dotted',false,false,'1321',null),
('school was','school of','group','counterpart_to',false,'dotted',false,false,'1322',null),
('worker was','worked with','group','counterpart_to',false,'dotted',false,false,'1332',null),
('successor of','predecessor of','group','counterpart_to',true,'dotted',false,false,'1411',null),
('predecessor of','successor of','group','focus_to',true,'dotted',false,false,'1412',null),
('administration overlaps with','administration overlaps with','group','symmetric',false,'dotted',false,false,'1413',null),
('joint venture with','joint venture with','group','symmetric',false,'dotted',false,false,'1414',null),
('founded by (group to group)','founded (group to group)','group','counterpart_to',true,'dotted',false,false,'1421',null),
('founded (group to group)','founded by (group to group)','group','focus_to',true,'dotted',false,false,'1422',null),
('related to (familial)','related to (familial)','family','symmetric',false,'dotted',true,true,'1500',null),
('sibling of','sibling of','family','symmetric',false,'dotted',true,true,'1501',null),
('child of','parent of','family','counterpart_to',true,'dotted',true,true,'1511',null),
('parent of','child of','family','focus_to',true,'dotted',true,true,'1512',null),
('grandchild of','grandparent of','family','counterpart_to',true,'dotted',true,true,'1513',null),
('grandparent of','grandchild of','family','focus_to',true,'dotted',true,true,'1514',null),
('great-grandparent of','great-grandchild of','family','focus_to',true,'dotted',true,true,'1515',null),
('great-grandchild of','great-grandparent of','family','counterpart_to',true,'dotted',true,true,'1516',null),
('cousin of','cousin of','family','symmetric',false,'dotted',true,true,'1521',null),
('nephew/niece of','uncle/aunt of','family','counterpart_to',true,'dotted',true,true,'1531',null),
('uncle/aunt of','nephew/niece of','family','focus_to',true,'dotted',true,true,'1532',null),
('spouse of','spouse of','family','symmetric',false,'dotted',true,true,'1541',null),
('consort of','consort was','family','symmetric',false,'dotted',true,true,'1542',null),
('consort was','consort of','family','symmetric',false,'dotted',true,true,'1543',null),
('significant other of','significant other of','family','symmetric',false,'dotted',true,true,'1544',null),
('romantic partner of','romantic partner of','family','symmetric',false,'dotted',true,true,'1547',null),
('domestic partner of','domestic partner of','family','symmetric',false,'dotted',true,true,'1548',null),
('relative by marriage (in-law)','relative by marriage (in-law)','family','symmetric',false,'dotted',true,true,'1550',null),
('sibling by marriage (in-law) of','sibling by marriage (in-law) of','family','symmetric',false,'dotted',true,true,'1551',null),
('parent by marriage (in-law) of','child by marriage (in-law) of','family','focus_to',true,'dotted',true,true,'1552',null),
('child by marriage (in-law) of','parent by marriage (in-law) of','family','counterpart_to',true,'dotted',true,true,'1553',null),
('adoptive parent of','adoptive child of','family','focus_to',true,'dotted',true,true,'1554',null),
('adoptive child of','adoptive parent of','family','counterpart_to',true,'dotted',true,true,'1555',null),
('half-sibling of','half-sibling of','family','symmetric',false,'dotted',true,true,'1556',null),
('step-sibling of','step-sibling of','family','symmetric',false,'dotted',true,true,'1557',null),
('step-child of','step-parent of','family','counterpart_to',true,'dotted',true,true,'1561',null),
('step-parent of','step-child of','family','focus_to',true,'dotted',true,true,'1562',null),
('guardian of','ward of','family','focus_to',true,'dotted',true,true,'1571',null),
('ward of','guardian of','family','counterpart_to',true,'dotted',true,true,'1573',null),
('godparent of','godchild of','family','focus_to',true,'dotted',true,true,'1574',null),
('godchild of','godparent of','family','counterpart_to',true,'dotted',true,true,'1575',null),
('descendent of','ancestor of','family','counterpart_to',true,'dotted',true,true,'1581','Getty spelling preserved'),
('founder of','founded by','group','focus_to',false,'dotted',false,false,'2572',null),
('founded by','founder of','group','counterpart_to',false,'dotted',false,false,'2573',null),
('director of','directed by','group','focus_to',false,'dotted',false,false,'2574',null),
('directed by','director of','group','counterpart_to',false,'dotted',false,false,'2575',null),
('professor at (person to institution)','professor was (institution to person)','group','focus_to',false,'dotted',false,false,'2674',null),
('professor was (institution to person)','professor at (person to institution)','group','counterpart_to',false,'dotted',false,false,'2675',null),
('teacher at (person to institution)','teacher was (institution to person)','group','focus_to',false,'dotted',false,false,'2676',null),
('teacher was (institution to person)','teacher at (person to institution)','group','counterpart_to',false,'dotted',false,false,'2677',null),
('student at (person to institution)','student was (institution to person)','group','focus_to',false,'dotted',false,false,'2828',null),
('student was (institution to person)','student at (person to institution)','group','counterpart_to',false,'dotted',false,false,'2829',null),
('ancestor of','descendent of','family','focus_to',true,'dotted',true,true,'1582',null),
('possibly related to (familial)','possibly related to (familial)','family','symmetric',false,'dotted',true,true,'1590','Uncertain familial relation retained as raw qualifier'),
('friend of','friend of','association','symmetric',false,'dotted',true,true,'2550',null),
('trustee of','trustee was','group','focus_to',false,'dotted',false,false,'2578',null),
('trustee was','trustee of','group','counterpart_to',false,'dotted',false,false,'2579',null),
('administrator of','administered by','group','focus_to',false,'dotted',false,false,'2581',null),
('administered by','administrator of','group','counterpart_to',false,'dotted',false,false,'2582',null),
('publisher was (person to institution)','publisher of','group','focus_to',false,'dotted',false,false,'2650',null),
('publisher of','publisher was (person to institution)','group','counterpart_to',false,'dotted',false,false,'2651',null),
('president of (person to institution)','president was (institution to person)','group','focus_to',false,'dotted',false,false,'2692',null),
('president was (institution to person)','president of (person to institution)','group','counterpart_to',false,'dotted',false,false,'2693',null),
('leader of (person to institution)','leader was (institution to person)','group','focus_to',false,'dotted',false,false,'2696',null),
('leader was (institution to person)','leader of (person to institution)','group','counterpart_to',false,'dotted',false,false,'2697',null),
('owner of','owned by','group','focus_to',false,'dotted',false,false,'2778',null),
('owned by','owner of','group','counterpart_to',false,'dotted',false,false,'2781',null),
('dedicatee of','dedicated by','patronage','focus_to',false,'dotted',false,false,'2782',null),
('dedicated by','dedicatee of','patronage','counterpart_to',false,'dotted',false,false,'2779',null),
('representative of (person to institution)','representative was (institution to person)','group','focus_to',false,'dotted',false,false,'2794',null),
('representative was (institution to person)','representative of (person to institution)','group','counterpart_to',false,'dotted',false,false,'2795',null),
('performer with (person to group)','performer was (group to person)','group','focus_to',false,'dotted',false,false,'2840',null),
('performer was (group to person)','performer with (person to group)','group','counterpart_to',false,'dotted',false,false,'2841',null)
on conflict (raw_qualifier) do update set
  reciprocal_qualifier=excluded.reciprocal_qualifier,
  normalized_family=excluded.normalized_family,
  direction_mode=excluded.direction_mode,
  directed=excluded.directed,
  visual_class=excluded.visual_class,
  expansion_eligible=excluded.expansion_eligible,
  render_eligible=excluded.render_eligible,
  getty_code=excluded.getty_code,
  notes=excluded.notes,
  active=true,
  updated_at=now();

-- RLS: v1 tables are server-administered through Vercel functions. No anonymous
-- browser writes are permitted. Service-role requests bypass RLS.
alter table public.v1_artists enable row level security;
alter table public.v1_networks enable row level security;
alter table public.v1_network_memberships enable row level security;
alter table public.v1_ulan_profiles enable row level security;
alter table public.v1_relationship_rules enable row level security;
alter table public.v1_ulan_relationship_assertions enable row level security;
alter table public.v1_unknown_qualifiers enable row level security;
alter table public.v1_network_candidates enable row level security;
alter table public.v1_curatorial_overrides enable row level security;
alter table public.v1_curatorial_relationships enable row level security;
alter table public.v1_media_cache enable row level security;
alter table public.v1_sync_runs enable row level security;
